### ISSUE TITLE
#!/usr/bin/env bash  should be #!/usr/bin/env sh

### ISSUE THREAD

**Issue by doug-descombaz** [wltiii/tcrman#2]
I believe `#!/usr/bin/env sh` is more portable than `#!/usr/bin/env bash`

https://github.com/wltiii/tcrman/blob/30b7a781060255ba83fb7fa0fbc940438f6b8766/variants/btcr#L1

**Comment by wltiii** [comment]
When a text file with a shebang is used as a command in a Unix-like operating system, the program loader mechanism parses the rest of the file's initial line as an interpreter directive. Using `/usr/bin/env {interpreter of choice}`, the loader will execute said interpreter. This could be python, groovy, or others, but quite commonly it is bash. The command interepreter `sh` does not necessarily equate to bash. Bash is available on most, if not all, unix-like operating systems, hence this is considered a safe and very portable request.

Since the project depends upon having globstar available, it is important to use a shell that supports it. This means bash 4 or greater. Perhaps others would be okay as well. I believe zsh supports it - have not tried nor researched that. If i learn more or get feedback from others, I will revisit this. For now using this idiom is a standard practice and is quite acceptable.

FWIW - Apple has not upgraded Bash for many years. The version is stuck at 3, which does not support globstar. Thus, Mac users will need to upgrade or try this using the `zsh` interpreter.
